version: '3'
services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=exam
    ports:
      - "${IP_DB}:3600:3600"
    command:
      - --innodb_use_native_aio=0
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - ../runtime/mysql:/var/lib/mysql
  api:
    build: api/.
    image: api
    container_name: examp_api
    volumes:
      - ./api/src:/var/www/src
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DSN_VALUE=mysql
    depends_on:
      - mysql
    links:
      - mysql:${DOMAIN_DB}
networks:
  default:
    external:
      name: examp
